name: CI/CD using Github Actions

on:
  workflow_run:
    workflows: ["Infrastructure Pipeline"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
